import mongoose from "mongoose";

const cropActivitySchema = new mongoose.Schema(
  {
    farmer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true
    },
    field: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "FarmField"
    },
    cropType: {
      type: String,
      required: true,
      trim: true,
      maxlength: 60
    },
    activityType: {
      type: String,
      required: true,
      enum: [
        "sowing", "irrigation", "fertilizer", "pesticide", "weeding",
        "pruning", "harvesting", "soil-test", "mulching", "thinning",
        "transplanting", "observation", "other"
      ]
    },
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 200
    },
    description: {
      type: String,
      trim: true,
      maxlength: 1000
    },
    scheduledDate: {
      type: Date,
      required: true
    },
    completedDate: Date,
    status: {
      type: String,
      enum: ["upcoming", "in-progress", "completed", "skipped", "overdue"],
      default: "upcoming"
    },
    priority: {
      type: String,
      enum: ["low", "medium", "high", "critical"],
      default: "medium"
    },
    isAutoGenerated: {
      type: Boolean,
      default: false
    },
    cost: {
      type: Number,
      min: 0,
      default: 0
    },
    inputUsed: {
      name: String,
      quantity: Number,
      unit: String
    },
    weatherNote: String,
    reminderSent: {
      type: Boolean,
      default: false
    }
  },
  { timestamps: true }
);

cropActivitySchema.index({ farmer: 1, scheduledDate: 1 });
cropActivitySchema.index({ farmer: 1, cropType: 1, status: 1 });

export default mongoose.model("CropActivity", cropActivitySchema);
